# Generated by Django 5.1.3 on 2024-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=2000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
